### ISSUE TITLE
Doc states MagicalCamera.SELECT_PHOTO instead MagicalCameraObject.SELECT_PHOTO

### ISSUE THREAD

**Issue by cutiko** [fabian7593/MagicalCamera#13]
Greetings

Documentation indicates that the code for the intentes (both camera and gallery) are a constant in MagicalCamera, but is not. It should be MagicalCameraObject instead.

This is very important cause I thought I had to use my own code and then MagicalCamera would magically do everything else, however, didnt workd untill I found ActionPicture class

```
public void resultPhoto(int requestCode, int resultCode, Intent data) {
        if (resultCode == Activity.RESULT_OK) {
            if (requestCode == MagicalCameraObject.SELECT_PHOTO) {
                this.actionPictureObject.setMyPhoto(onSelectFromGalleryResult(data));
            } else if (requestCode == MagicalCameraObject.TAKE_PHOTO) {
                this.actionPictureObject.setMyPhoto(onTakePhotoResult());
            }
        }
    }
```

Hope to help.

**Comment by fabian7593** [comment]
Hello @cutiko thanks for report the issue,
yes effectively the documentation of this part is completely wrong... Thanks very much.
This is because I remake the POO logic, because in the first and third version this haved a real code desorder, because in a first entry this library was completely simple, but grew up a litle.
