### ISSUE TITLE
how to use with proguard

### ISSUE THREAD

**Issue by Jahury** [fabian7593/MagicalCamera#20]
when I want to make a release with proguard it give me an error 
how to exclude it from proguard

**Comment by fabian7593** [comment]
Hello @Jahury.
Remember that, the library import in gradle this libraries:

- compile 'com.android.support:appcompat-v7:24.0.0-alpha1'
- compile 'com.google.android.gms:play-services-location:10.2.0'
- compile 'com.google.android.gms:play-services-vision:10.2.0'

For use the exif inteface, for obtain the information of the picture.
Then, in my opinion you need to implement the last libraries and magical camera, maybe like this:
-keep class magicalcamera.** { *; }

or like
-keep class com.frosquivel.magicalcamera.** { *; }

Why?
because magical camera is a free and open source library, you dont need to worry of realize a proguard in this, in my opinion only need to exclude the library.

I am not a master of proguard, you can need to search in stack overflow maybe like this:
http://stackoverflow.com/questions/7721397/how-to-make-proguard-ignore-external-libraries


**PD: This is not a issue of magical camera, you need to implement any method for exclude the library in proguard.**
