### ISSUE TITLE
Change default  storage directory

### ISSUE THREAD

**Issue by rsanabria** [fabian7593/MagicalCamera#23]
Using `magicalCamera.savePhotoInMemoryDevice(magicalCamera?.getPhoto(),"foto",this.externalCacheDir.toString(), MagicalCamera.JPEG, true);`
 is saving in: 
> /storage/emulated/0/Pictures/storage/emulated/0/Android/data/com.package.example/cache/foto_20170419155537.jpeg

Is there a way to avoid saving the photo in the gallery path (/storage/emulated/0/Pictures/storage)...? 
By the way I'm using kotlin

**Comment by fabian7593** [comment]
Hello @rsanabria,
I dont know if use kotlin affect with magical camera really... Because I never use that, although I believe that not generate any problem...
well...

In this version, MagicalCamera not support save the picture in cacheDir, only in gallery either internal or external memory, but for the next versions I will keep it in mind.

Thanks for your issue contribution.

In this moment I offer this method:
magicalCamera.savePhotoInMemoryDevice(magicalCamera.getPhoto(), "myTestPhotoName", "myDirectoryName", MagicalCamera.JPEG, true);

PD: "myDirectoryName" = only the name of your directory, not all the path.
This save in a path of gallery, with the name of directory that you need.
