### ISSUE TITLE
Samsung devices with rotated images

### ISSUE THREAD

**Issue by manelv8** [fabian7593/MagicalCamera#25]
I've  tested the sample app with old samsung galaxy s2 lite and galaxy j5. Both had the same problem, the picture from back camera was rotated to left, and the one from front camera was rotated to right.
Some pictures from album had the same behavior. Any ideia how can I solve this issue?

**Comment by fabian7593** [comment]
Hello @manelv8  thanks for use Magical Camera,

This issue is for the Samsung maker and any others brands or/and models.

This issue is because the camera hardware is in horizontal, not in vertical like another brands, and the real real problem is that the ExifInterface class return an variable with "is Vertical Picture" in true.

In any case I made the posibillity of rotate picture manually with:
https://github.com/fabian7593/MagicalCamera#rotate-picture

You can made the posibillity of rotate picture manually for the user, or that have, for example: "if is samsung? rotate to right"...

This issue was/is in any apps (include facebook in any time), but I dont have all device for test this, and the simulator dont have this problem.
