### ISSUE TITLE
magicalCamera.getPrivateInformation().getOrientation() is returning null

### ISSUE THREAD

**Issue by ardakaplan** [fabian7593/MagicalCamera#37]
Hi Fabian,

I need to know what is the orientation of photo. What is the correct way to do it ? Depends on it, i should rotate the image

**Comment by fabian7593** [comment]
hI @ardakaplan 
Yes in android devices this is an common issue, because for example samsung device have the camera in landscape mode, different to others devices.
Then, the get orientation with ExifInterface, isnt a solution for this issue...
I think that the solution always was measure the photo, and determinate with the result, if is potrait or landscape orientation...

I need to fix it, but in another version
