### ISSUE TITLE
FileUriExposedException in Fragment

### ISSUE THREAD

**Issue by camposvo** [fabian7593/MagicalCamera#46]
Hi, i am get this error : 
android.os.FileUriExposedException: file://com.frosquivel.magicalcamera.Provider.PhotoProvider/storage/emulated/0/Android/data/com.example.smr.scc1/files/Pictures/MagicalCamera/MagicalCamera exposed beyond app through ClipData.Item.getUri()

I am using 'com.frosquivel:magicalcamera:6.0.0'
I really apreciate your help...

**Comment by fabian7593** [comment]
Hello,
yeah I'm sorry, I forget to update the Readme file.
You need to implements this method to works the getUri, and all library magicalcamera on any devices with any SDK's versions.

https://github.com/fabian7593/MagicalCamera/blob/master/README.md#extends-application-class

**Comment by deb-anndy** [comment]
Hi, the issue is still there
FileUriExposedException in Activity
android.os.FileUriExposedException: file://com.frosquivel.magicalcamera.Provider.PhotoProvider/storage/emulated/0/Android/data/
Device: Galaxy J7 nxt
Ram/Rom: 2Gb/16Gb

I am using 6.0.0 version
Also i install the Magical Camera App from play store and check ,same issue there

**Comment by fabian7593** [comment]
The play store app is not update.
Github project have the last project version, with the current fix
