### ISSUE TITLE
java.lang.SecurityException: Permission Denial: starting Intent on Mashmallow 23

### ISSUE THREAD

**Issue by AndroidKrayze** [fabian7593/MagicalCamera#6]
Hello Fabian, tested on Mashmallow as I need it for my app but I get security problems.

I have attached a full stack trace of the error while Running on Mashmallow

https://gist.github.com/AndroidKrayze/32aa284942b3f4e32c9366daf6894e0d

**Comment by fabian7593** [comment]
Hello AndroidKrayze, thanks for report the issue...
I believe that this problem is for the manifest configuration, if you stay
the example's magical camera of github, plase modify the manifest with this:

https://gist.github.com/fabian7593/152224835233477b22e97b02df876667

If you be work in your own project, add the line  android:exported="true"*
in your activity properties.*
and review if your "run app" in android studio is selected (or if the debug
option have the main activity in launch).

Thanks,

If your issue not fix please contact me again.

2016-07-14 2:42 GMT-06:00 AndroidKrayze notifications@github.com:

> Hello Fabian, tested on Mashmallow as I need it for my app but I get
> security problems.
> 
> I have attached a full stack trace of the error while Running on Mashmallow
> 
> https://gist.github.com/AndroidKrayze/32aa284942b3f4e32c9366daf6894e0d
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/fabian7593/MagicalCamera/issues/6, or mute the thread
> https://github.com/notifications/unsubscribe/AMua5ZZxD-1QJikoySl8qylNMCi-a98Hks5qVfZcgaJpZM4JMNMn
> .

## 

_Fabián Rosales Esquivel_
*Analyst and Software Developer *

Frosquivel Developer
If you can dream, you can do it.

Desamparados, San José, Costa Rica
_Mobile:_ (506) 8346 1166
_Portfolio: *www.frosquivel.com  http://www.frosquivel.com
*Blog: *
*www.frosquivel.com/blog  http://www.frosquivel.com/blog  *_GitHub:
*_https://github.com/fabian7593
https://github.com/fabian7593_
-  https://github.com/fabian7593*fabian7593@gmail.com
  [image: skype]fabianre7593

**Comment by AndroidKrayze** [comment]
Gracias Fabian!!!!!!!!!!! I will have a look and let you know.

**Comment by fabian7593** [comment]
@AndroidKrayze Hello,
In the current version of magicalCamera 4.8, you have the possibility of take the picture in device of any version... you need to call the PermissionGranted Class, and pass the variable in magical camera constructor...
Please test this for use magical camera and check the new documentation,
Thanks
